### ISSUE TITLE
Bot not working

### ISSUE THREAD

**Issue by Madalin-Vis** [Barsik008/PossumBot#65] opened 2020-12-07 11:56 UTC
i type !arturdebil and the bot does nothing .........

i get this message : 

TypeError: message.guild.members.filter is not a function
    at Object.module.exports.run (D:\PROTECTED FROM ANTIVIRUS\PossumBot-master\commands\arturdebil.js:7:31)
    at Client.<anonymous> (D:\PROTECTED FROM ANTIVIRUS\PossumBot-master\bot.js:64:7)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (D:\PROTECTED FROM ANTIVIRUS\PossumBot-master\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (D:\PROTECTED FROM ANTIVIRUS\PossumBot-master\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (D:\PROTECTED FROM ANTIVIRUS\PossumBot-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (D:\PROTECTED FROM ANTIVIRUS\PossumBot-master\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (D:\PROTECTED FROM ANTIVIRUS\PossumBot-master\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (D:\PROTECTED FROM ANTIVIRUS\PossumBot-master\node_modules\ws\lib\event-target.js:125:16)
    at WebSocket.emit (events.js:315:20)

**Comment by Barsik008** [comment] 2020-12-07 12:12
Duplicate of #52

**Closed by Barsik008** 2020-12-07 12:12 UTC
